#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# fixes x shaped cursor
xsetroot -cursor_name left_ptr

# clear out screenshots folder
rm -rf ~/.cache/screenshots/*

# wallpaper
xwallpaper --no-randr --center ~/pictures/wallpapers/otter.png

# config
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc config border_width         3
bspc config window_gap           12
bspc config top_padding          25
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# colorscheme
bspc config focused_border_color "#ffd1dc"
bspc config normal_border_color  "#616161"

# application rules
bspc rule -a Steam desktop=^9

# autostart 
picom &
killall -q polybar
polybar example -q
