#! /bin/sh

# config 
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width         3
bspc config window_gap           12
bspc config top_padding          22
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# colorscheme
bspc config focused_border_color "#a57562"
bspc config normal_border_color  "#5e4c44"

# autostart 
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/Pictures/Wallpapers/rosebox.png
killall -q polybar
polybar example -q
